version: '3'
services:
  db:
    image: orientdb
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    volumes:
      - ./orientdb/databases:/opt/orientdb/databases
  web:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db